[RFC] Created PhpStorm inspections settings profile
ezsystems/ezplatform-code-style pull request #1
Opened 2019-09-12 15:10 UTC by alongosz

I've added PhpStorm inspections settings profile, intended for importing by every Contributor of eZ Platform-related packages.

In this PR we can discuss enabling/disabling different settings.

2020-09-16 13:34 UTC, dabrt requested changes

2020-09-16 13:34 UTC, dabrt commented on README.md
> +See the [IDE/PhpStorm/PhpStormInspections.xml](./IDE/PhpStorm/PhpStormInspections.xml) for
```suggestion
See the [PhpStormInspections.xml](./IDE/PhpStorm/PhpStormInspections.xml) file for
```

2020-09-16 13:34 UTC, dabrt commented on README.md
> +the PhpStorm code inspections settings profile. The profile can be imported by choosing:
```suggestion
the PhpStorm code inspections settings profile. 
To import the profile, click:
```

2020-09-16 13:34 UTC, dabrt commented on README.md
> +File -> Settings -> Editor -> Inspections > Import profile
```suggestion
File -> Settings -> Editor -> Inspections -> Import profile
```

2020-09-16 13:34 UTC, dabrt commented on README.md
> +
```suggestion


For more information, see the [PhpStorm documentation](https://www.jetbrains.com/help/phpstorm/customizing-profiles.html#47e75).


```

2020-09-16 13:51 UTC, alongosz commented on IDE/PhpStorm/PhpStormInspections.xml
> +  <option name="myName" value="eZ" />
Well, that's soo outdated

```suggestion
  <option name="myName" value="Ibexa" />
```

2020-09-17 12:47 UTC, dabrt approved these changes

2022-02-24 11:09 UTC, alongosz commented
This is quite outdated and based on internal discussions quite a while ago, it's not the best place to keep IDE-specific config.
Right now the go-to tool to help working with Ibexa DXP is [Ibexa DXP Plugin for PHPStorm](https://plugins.jetbrains.com/plugin/17239-ibexa-dxp)

2022-02-24 11:09 UTC, closed without merging