Fix PHP-CS-Fixer v2 -> v3 deprecations
ezsystems/ezplatform-code-style pull request #13
Opened 2021-06-29 12:01 UTC by Steveb-p

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | N/A, internal
| **Type**                                   | improvement
| **Target package version** | ?
| **BC breaks**                          | no
| **Doc needed**                       | no

Before:
```
composer fix-cs
> @php ./vendor/bin/php-cs-fixer fix -v --show-progress=estimating
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.20
Loaded config default from "/home/steveb/PhpstormProjects/ezplatform-code-style/.php_cs".
Using cache file ".php_cs.cache".
....                                                                4 / 4 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.121 seconds, 14.000 MB memory used

Detected deprecations in use:
- A list of elements is deprecated, use a dictionary of `const|method|property` => `none|one` instead.
- Configuration file `.php_cs` is deprecated, rename to `.php-cs-fixer.php`.
- Option "commentType" is deprecated, use "comment_type" instead.
- Passing `estimating`, `estimating-max` or `run-in` is deprecated and will not be supported in 3.0, use `none` or `dots` instead.
- Rule "lowercase_constants" is deprecated. Use "constant_case" instead.
- Rule "phpdoc_inline_tag" is deprecated. Use "general_phpdoc_tag_rename", "phpdoc_inline_tag_normalizer" and "phpdoc_tag_type" instead.
- Rule "psr4" is deprecated. Use "psr_autoloading" instead.
- Rule "trailing_comma_in_multiline_array" is deprecated. Use "trailing_comma_in_multiline" instead.
```

After:
```
composer fix-cs
> php-cs-fixer fix -v --show-progress=dots
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.20
Loaded config default from "/home/steveb/PhpstormProjects/ezplatform-code-style/.php-cs-fixer.php".
Using cache file ".php_cs.cache".
....                                                                                                                                                                                                                        4 / 4 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
```

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Checked that target branch is set correctly.
- [x] Asked for a review (ping `@ibexa/engineering`).

2021-06-29 15:03 UTC, adamwojs approved these changes

2021-07-05 12:13 UTC, alongosz requested changes

2021-07-05 12:13 UTC, alongosz commented on .php-cs-fixer.php
> +use Ibexa\Platform\CodeStyle\PhpCsFixer\InternalConfigFactory;
https://github.com/ezsystems/ezplatform-code-style/pull/10#pullrequestreview-699113742

2021-07-05 18:49 UTC, merged

2021-07-05 18:51 UTC, Steveb-p commented
Accidentaly pushed the changes into `ibexa-namespace` branch :sweat_smile: