Added rule to force using FQCN in DocBlock comments
ezsystems/ezplatform-code-style pull request #8
Opened 2021-03-03 21:38 UTC by adamwojs

> JIRA: -

### Description

Added rule to force using FQCN in DocBlock comments.

2021-03-03 21:39 UTC, Steveb-p approved these changes

2021-03-04 11:44 UTC, alongosz requested changes
We need to consult usage of `adamwojs/php-cs-fixer-phpdoc-force-fqcn` (MIT license) in this package with @lserwatka
+1 from my side.

2021-03-16 08:27 UTC, lserwatka commented
@alongosz We will move Adam's package to Ibexa later as open source. For now it is ok.

2021-03-16 08:31 UTC, alongosz approved these changes

2021-03-16 08:31 UTC, merged